DockYard/ember-one-way-controls

- README.md
> Update readme with explanation of cursor jump issue

- .travis.yml
> Use a real browser

- addon/components/one-way-input.js
Adds binding for the 'maxlength' attribute of input
> Adds the binding of the maxlength attribute

- addon/components/one-way-input.js
- tests/acceptance/main-test.js
- tests/dummy/app/controllers/application.js
- tests/dummy/app/templates/application.hbs
> Fix bug with inputting decimal places with number inputs

- addon/components/one-way-select.js
- addon/components/one-way-select/option.js
- addon/helpers/contains.js
- addon/index.js
- addon/templates/components/one-way-select.hbs
- addon/templates/components/one-way-select/option.hbs
- app/components/one-way-select.js
- app/components/one-way-select/option.js
- app/helpers/contains.js
- package.json
- tests/integration/components/one-way-select-test.js
In advance of the `one-way-controls` rename.
> Added {{one-way-select}}

- addon/components/one-way-input.js
- tests/integration/components/one-way-input-test.js
> Fixes "echo updates"

- tests/acceptance/main-test.js
- tests/integration/components/one-way-input-test.js
These tests are not fixed.
I have reopened #16 to track the progress on fixing the issue.
> Skips decimal tests

- config/ember-try.js
- package.json
to get ready for npm changes in try scenarios
> update ember-try to 0.1.x

- README.md
> Add install instruction

- addon/components/one-way-input.js
- tests/integration/components/one-way-input-test.js
> Dynamically bind attributes

- README.md
- addon/components/one-way-input.js
- package.json
- tests/integration/components/one-way-input-test.js
Needs to be rebased once #67 is merged in.
> Allow custom key events to be specified

- README.md
- docs/one-way-checkbox.md
- docs/one-way-input.md
- docs/one-way-select.md
I want add one readme file for each type of control and then link to them from README.md
> Improve documentation

- addon/components/one-way-radio.js
- app/components/one-way-radio.js
- tests/integration/components/one-way-radio-test.js
In advance of the `one-way-controls` rename.
> Added {{one-way-radio}}

- addon/components/one-way-input.js
- tests/integration/components/one-way-checkbox-test.js
> Accept outside toggle of checked

- addon/components/one-way-checkbox.js
- addon/components/one-way-input.js
- addon/components/one-way-radio.js
- addon/components/one-way-select.js
- tests/integration/components/one-way-checkbox-test.js
Fixes #83
Strictly this update isn't needed on every control, but I feel like it
cant hurt either.
> Fix faulty shortcircuit logic

- addon/templates/components/one-way-select.hbs
- addon/templates/components/one-way-select/option.hbs
- docs/one-way-select.md
- tests/integration/components/one-way-select-test.js
Needs more work on docs and I d'like to add more tests but I would love a first review. Do we agree on this change? If not, are there better options to achieve the use case?
> Support block expressions

- addon/components/one-way-checkbox.js
- addon/components/one-way-input.js
- addon/components/one-way-radio.js
- addon/components/one-way-select.js
- addon/templates/components/one-way-select.hbs
- tests/integration/components/one-way-checkbox-test.js
- tests/integration/components/one-way-input-test.js
- tests/integration/components/one-way-radio-test.js
- tests/integration/components/one-way-select-test.js
> Bugfix: positional param value update to null or undefined

- addon/components/one-way-input.js
- tests/dummy/app/controllers/application.js
- tests/dummy/app/templates/application.hbs
- tests/integration/components/one-way-input-test.js
> Fixes input masking problem

- addon/components/one-way-input.js
- tests/integration/components/one-way-input-test.js
> Fix cursor jumping issue

- addon/components/one-way-input.js
- tests/integration/components/one-way-input-test.js
> Add guards clauses to selection fix

- addon/components/one-way-input.js
- package.json
- tests/integration/components/one-way-input-test.js
> Refactor one-way-input, fixes masking + cursor position bugs

- addon/components/one-way-select.js
- addon/helpers/one-way-select/contains.js
- addon/templates/components/one-way-select.hbs
- addon/templates/components/one-way-select/option.hbs
- docs/one-way-select.md
- tests/integration/components/one-way-select-test.js
> Add the optionTargetPath option

- package.json
- yarn.lock
> Update "ember-cli" to v2.16.2

- package.json
- yarn.lock
... to get rid of the Babel 5 dependency :)
> Update "ember-invoke-action" to v1.5.0
